---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine  # Sets Deployment name
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
        - name: redmine
          image: redmine:4.1.1 # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3000  # Exposes container port
          envFrom:
            - secretRef:
                name: redmine-secret
            - configMapRef:
                name: postgres-config
